### ISSUE TITLE
Pressing 'D' when text is selected deletes an extra line

### ISSUE THREAD

**Issue by jordwalke** [sublimehq/Vintage#10]
As titled.

**Comment by wilkerlucio** [comment]
tried here, it's working fine (no extra line deleted). I think it could be another plugin that you have making the wrong behavior.

**Comment by netpro2k** [comment]
I am also unable to reproduce this

**Comment by wilkerlucio** [comment]
but I saw another problem, try to do a selection like this: http://cl.ly/462X1G2k0c1M143f1Y1N using regular "v" key, and them just delete with "d". It will delete the entire lines, instead of just the selection...

**Comment by netpro2k** [comment]
Indeed, I can also reproduce this second issue

**Comment by netpro2k** [comment]
Looks like it was just an incorrect setting in keybindings. 

```
"motion_mode": "auto_line"
```

Means to expand the selection to full lines if it spans more than 1 line. I have submitted a pull request:

https://github.com/sublimehq/Vintage/pull/16

**Comment by misfo** [comment]
#59 fixed all cases of this that I've experienced. Feel free to re-open this if you're still experiencing it
