### ISSUE TITLE
dw broken when used on last word of a line

### ISSUE THREAD

**Issue by eoinkelly** [sublimehq/Vintage#12]
Hi,
When I position my cursor on the last word of a line and execute _dw_ it deletes the EOL and the next line. For example

```
lorem ipsum hello
foo sit amet
sed pulvinar bar
```

If you position your customer under the _h_ in _hello_ and execute **dw** it deletes all the way to _sed_. I am using the Sublime Text 2 Beta Build 2139 and the master git version of Vintage. Thanks for your time.
/Eoin/

**Comment by misfo** [comment]
This is fixed on `master` and in the latest build
