### ISSUE TITLE
Going into command mode, then back to insert mode moves cursor back

### ISSUE THREAD

**Issue by charlesroper** [sublimehq/Vintage#144]
Here's a video of of me going in and out of command mode: http://screencast.com/t/AUtRezT0Xb. You can clearly see the cursor going back one character each time.

**Comment by quarnster** [comment]
Which is exactly what vim does also.

**Comment by misfo** [comment]
It works that way in Vim as well...

**Comment by charlesroper** [comment]
Fair enough. :-)
