### ISSUE TITLE
ST3: using ';' to repeat last jump doesn't work.

### ISSUE THREAD

**Issue by evantravers** [sublimehq/Vintage#179]
I'm was pretty sure that this worked before, and I know it works in ST2, so it may very well be me. After doing a jump, like f. to jump to the first period in a line, normally you can hit ; to repeat the jump (in this case going to the next period) but this is not functioning in my version of ST3.

**Comment by adri** [comment]
+1 
I noticed exactly the same after switching to ST3.

**Comment by greyshi** [comment]
+1; specific to ST3; is annoying.

Also, using "," to go to the previous occurrence doesn't work.

This repo hasn't been updated for a year, so maybe I should just go back to ST2 :(.

**Comment by guillermooo** [comment]
@Aghoreyshi You may want to try https://github.com/guillermooo/Vintageous

**Comment by greyshi** [comment]
Haha I've just installed that and am configuring it now! Hopefully it doesn't have problems of its own.

**Comment by evantravers** [comment]
I ended up in neovim. Closing this.
