### ISSUE TITLE
If the cursor is on the final line of the file 'dd' should delete backwards.

### ISSUE THREAD

**Issue by keyneston** [sublimehq/Vintage#193]
Normally `dd` will delete the the current line in the file. If your cursor is on the final line of the file then Vim will delete the previous line.

**Comment by RLGyde** [comment]
I can't replicate that Vim behavior @tarrant.
But what sublime vintage don't do is to delete the current line when `dd` is used on the last line. It deletes all chars on the line, but not the new line chars at the end of the previous line.

I think it would be nice if sublime vintage did have the same behavior as vi/vim in this respect.

**Comment by keyneston** [comment]
I have no idea what I was writing when I created this ticket. Yes `dd` deletes the current line and then moves the cursor up a line.
