### ISSUE TITLE
Simple motions give incorrect result

### ISSUE THREAD

**Issue by tdegrunt** [sublimehq/Vintage#20]
I would expect `40i-<Esc>` to insert 40 - characters.

If I have a file, with one line with the text "Hello World" and do: `YpVr-`, I would expect that to result in:

```
Hello World
-----------
```

Instead it turns it into:

```
----------------------
```

If you have a buffer with two lines, the same command turns the text into:

```
Hello World
------------
```

(One too many `-`)

**Comment by misfo** [comment]
Split this issue up into its individual issues:
#52, #100, #101
