### ISSUE TITLE
VIM ‘V + kkkkkkkkk…’ or ‘V + jjjjjjjjjjjjjjjjjjjj…’ makes the scroll crazy

### ISSUE THREAD

**Issue by tcha-tcho** [sublimehq/Vintage#208]
I don't know why, but working with caret in Vim in selecting mode (with 'v'). Going up or down (using arrows or 'k'/'j') will make the scroll goes up and down like a crazy. (Dev Channel build 3189)

This is only a problem in the development builds (I think this bug exists for all the development builds). The stable build works fine. Maybe it is an issue with the development builds, but not sure where to report the bug.

To reproduce, remove "Vintage" from the "ignored_packages" from settings; open a long document, at least three screens in length; press "ESC" to enter command mode, press "v" to enter visual mode; then press "j"/"k" or the arrows a few times to move the caret up/down a few lines. The screen will jump up and down.

**Comment by rdeits** [comment]
This issue appears to be present in the latest build 3200 release. As soon as approximately one screenful of lines has been selected in Vintage visual mode, every alternate press of the `j` key causes the screen to scroll back to the beginning of the selected text, and every other press causes the screen to scroll to the end of the selected text. The result is that the scroll jumps back and forth from the beginning to the end of the text with each press of `j`.

**Comment by tcha-tcho** [comment]
With arrow keys as well

**Comment by tcha-tcho** [comment]
The problem was solved in the version 3205. Thank you guys! :)
