### ISSUE TITLE
% motion works incorrectly

### ISSUE THREAD

**Issue by grayrest** [sublimehq/Vintage#23]
The vim behavior is search forward for a matchpair opener, if one is found on the same line, jump to the matchpair closer. If no matchpair is found forward on the same line, do nothing.

**Comment by misfo** [comment]
With vanilla Vim 7.3 (MacVim) `%` crosses line boundaries. It wouldn't be very useful if it didn't! Are you not seeing the same thing?

**Comment by grayrest** [comment]
I'm on Vim 7.2.103 running with `vim -N --noplugin -u emptyfile` to clear out all customizations with the text:

```
def
name (
)
```

If you're on the first line, pressing % does nothing. If you're anywhere on the second, it jumps you to the closing paren on the third line.

**Comment by misfo** [comment]
I see now. I forgot that Vim searches forward for a bracket on the line.  This should be fixed by #86
