### ISSUE TITLE
Feature: GoTo line, etc not implmented

### ISSUE THREAD

**Issue by chrisgeo** [sublimehq/Vintage#31]
I know GoTo "line number" etc is implemented in sublime text but being a vim user I'm used to ":" (or command) and a <num> sending me directly there and would be a great feature for vintage.

**Comment by guillermooo** [comment]
Try https://github.com/SublimeText/VintageEx

If it makes the grade, it might end up merged with Vintage, but at the moment I'm tearing my hair out with some regex testing... `:<address>` should work well, however. If you are a Mac OSX user, any feedback is very much welcome. I cannot test on Macs.

A number of ex commands are implemented too: `delete`, `copy`, `move`, `substitute`, `w`, `q`, `wall`, `global`, `!`, `r!`, `shell` and more.

**Comment by chrisgeo** [comment]
@guillermooo Looks great so far. Had to get used to ":" not doing the normal shift+cmd+p action :)
Was almost hoping search/replace would work (but admittedly that's pretty difficult to mimic).

**Comment by guillermooo** [comment]
> Was almost hoping search/replace would work (but admittedly that's pretty difficult to mimic).

Isn't it working? Open an issue at https://github.com/SublimeText/VintageEx and I'll look into it. Simple --and not-so-simple-- cases should actually work now.

**Comment by chrisgeo** [comment]
@guillermooo Works great for the simple case. For some reason it wasn't a few days ago. Thanks!
