### ISSUE TITLE
Holding down hjk or l doesnt move the cursor

### ISSUE THREAD

**Issue by krzkrzkrz** [sublimehq/Vintage#37]
Holding down `hjk` or `l` doesnt move the cursor. So in command mode, if I wanted to move down 10 lines. I would have to manually tap `j` 10 times. 

If I hold the `j` key down, it only moves the cursor down once...

**Comment by sublimehq** [comment]
This is an OS X issue, see http://www.sublimetext.com/docs/2/vintage.html
