### ISSUE TITLE
Goto line number in command mode does not work

### ISSUE THREAD

**Issue by krzkrzkrz** [sublimehq/Vintage#38]
Would like to be able to goto line numbers via command mode. For example: `12gg` would go to line 12. Anyone know why this isnt working?

**Comment by guillermooo** [comment]
Shouldn't that be `20G` instead of `20gg`?

**Comment by krzkrzkrz** [comment]
Yea both seem to work in MacVim. 

`20G` works in Vintage, while `20gg` does not

**Comment by codingcampbell** [comment]
I also find typing `gg` easier than `G`, and it is a standard vim feature.

**Comment by guillermooo** [comment]
Addressed in pull request #48.
