### ISSUE TITLE
<ESC> should quit visual mode

### ISSUE THREAD

**Issue by alvivi** [sublimehq/Vintage#5]
Currently, we have to press again `v` to quit visual mode.

**Comment by sublimehq** [comment]
What version of Sublime Text 2 are you running?

Escape exits visual mode (and visual line mode) when I press it here.

**Comment by alvivi** [comment]
Ok sorry, I updated to the last version and now is working quite right.

By the way, I found another little "bug". `V` doesn't quit visual line mode when visual line mode is active. I'm not sure what I'm doing (that's why I didn't make a pull request), but I've solved it with this:

``` python
class ExitVisualLineMode(sublime_plugin.TextCommand):
    def run(self, edit):
        set_motion_mode(self.view, MOTION_MODE_NORMAL)
        self.view.run_command('shrink_selections')
        self.view.run_command('unmark_undo_groups_for_gluing')
```

``` javascript
    { "keys": ["V"], "command": "exit_visual_line_mode",
        "context":
        [
            {"key": "setting.command_mode"},
            {"key": "selection_empty", "operator": "equal", "operand": false, "match_all": false}
        ]
    }
```
