### ISSUE TITLE
Allow "." to repeat last insert mode actions.

### ISSUE THREAD

**Issue by zolrath** [sublimehq/Vintage#55]
In vim if you go into insert mode, type something, and then hit esc that action is repeated when you press "."
Right now . will repeat actions like dd but it does nothing if your last action was input.

**Comment by misfo** [comment]
Is there a specific case where `.` doesn't repeat the insert? Seems to work for me...

**Comment by zolrath** [comment]
Hm that's odd, it doesn't work in any cases for me. I can use it to repeat dw and other actions but it doesn't repeat insert actions such as i hello or A somethingappended.

**Comment by misfo** [comment]
Can you install the plugin from master branch from this repo and test it again?

Is anyone else having this issue?

**Comment by zolrath** [comment]
Just did some tests and I think it may have been the BlockCursor package I had installed. It made the cursor look more like vim but certainly made it act less like it. Problem wasn't on your end!
