### ISSUE TITLE
:#,#d doesn't correctly paste

### ISSUE THREAD

**Issue by ghost** [sublimehq/Vintage#57]
When you use the :#,#d syntax, the contents put into the paste buffer is truncated.  For example, lets say you have a file that looks like this:

```
1:  
2:  hey
3:  there
4: 
5:  guys
6:
```

If you input    `<escape>`,  `:2,3d`, `<enter>`, go to line 5, `<escape>`, `p`, you should see this output:

```
1:  
2:  
3:  
4: 
5:  guys
6:  hey
7:  there
```

**Comment by misfo** [comment]
Vintage doesn't aim to emulate Vim ex, but there is a plugin that does: https://github.com/SublimeText/VintageEx
