### ISSUE TITLE
[Bug] Delete/Change/Select to a mark doesn't work

### ISSUE THREAD

**Issue by ashokgelal** [sublimehq/Vintage#6]
Somebody has already posted this issue on Sublime forum http://www.sublimetext.com/forum/viewtopic.php?f=2&t=2921 since nobody has replied to that post, I'm reposting this again here as I'm being limited by the lack of this feature.

"
In Vintage mode, if you set a mark (ex. by pressing "ma"), and then move the cursor somewhere else and try to delete to the mark (ex. by pressing "d`a"), the cursor just moves to the mark instead of deleting to the mark. This also happens when trying to select to the mark, copy to the mark, or change to the mark.
"

**Comment by misfo** [comment]
Right now marks use Sublimes standard bookmarking commands. Since the select bookmark command is not a motion, operators don't work with it.

These fixes could be made, but we'd have to make custom commands rather than the built-in bookmarking ones.
