### ISSUE TITLE
"j" and "k" not working

### ISSUE THREAD

**Issue by dtan** [sublimehq/Vintage#71]
After enabling Vintage, `j` and `k` do not go up or down, respectively, but `h` and `l` work perfectly fine.  any reason why some key mappings are working but others aren't?

**Comment by sublimehq** [comment]
j and k are working for me - it's worth trying with a clean install: http://www.sublimetext.com/docs/2/revert.html

**Comment by misfo** [comment]
Please reopen this issue if you're still experiencing the problem

**Comment by dtan** [comment]
ah, missed your first comment, but j and k seem to be working for build 2181
