### ISSUE TITLE
va is partially broken in visual mode

### ISSUE THREAD

**Issue by guillermooo** [sublimehq/Vintage#79]
`a` won't take you out of visual mode as it should:

`va` should exist visual mode and leave the caret after the selection, but instead it does nothing (visible). Pressing `a` again inserts `aa`.

**Comment by guillermooo** [comment]
The above is wrong too. Vim only exits visual mode if you press `A` or `I` and places you at the corresponding edge of the visual selection. `a` does nothing in visual mode.

**Comment by misfo** [comment]
Sounds like this isn't an issue (?). If not, feel free to reopen
