### ISSUE TITLE
Adding settings file for Vim options

### ISSUE THREAD

**Issue by guillermooo** [sublimehq/Vintage#84]
Someone asked in the forums how to set copy ops to always use the system's clipboard. This seems easy enough to fix with a `Vintage.sublime-settings` file.

Would this be desirable?

**Comment by sublimehq** [comment]
Probably best to just use an additional setting in the regular Preferences.sublime-settings file, to fit in with vintage_ctrl_keys and friends

**Comment by guillermooo** [comment]
K.
