### ISSUE TITLE
Paste does not paste over selected content.

### ISSUE THREAD

**Issue by jordwalke** [sublimehq/Vintage#9]
If you yank some text, then select some other text for pasting over - type 'p', it does not paste over the selected content.

**Comment by jordwalke** [comment]
Any thoughts on this?

**Comment by misfo** [comment]
It would be really nice for this to work like it does in Vim. Might be kinda tricky, though, since Vim pastes from the specified register and then puts the pasted-over text into that same register...

**Comment by jordwalke** [comment]
Even just getting it to paste over the content (without replacing the register) would be a great start. TBPH, I almost wish Vim acted this way by default.

**Comment by jordwalke** [comment]
@misfo have you found a way to get this to work - even if not perfectly - after the cursor position bug, this seems to be the last remaining major issue.

**Comment by jordwalke** [comment]
Does anyone have any pointers here?

**Comment by misfo** [comment]
Turns out the fix was pretty simple: 52622a7

**Comment by misfo** [comment]
This is fixed on `master` and in the latest build
